name: data-test

on: 
  push:
    branches: [ "main" ]

jobs:
  data1:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CODE1 }}
  data2:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CODE2 }}
